### ISSUE TITLE
documentation needed around 2's compliment

### ISSUE THREAD

**Issue by weisjohn** [tessel/ir-attx4#27]
I tried reading both the example code as well as the C implementation and couldn't find anything about how this is implemented: The README.md mentions the idea of a 2's complement system for representing the "off" signal durations. How do you know when you're dealing with an "off" number, is it just every other number?

> off for 4400 microseconds (0xeed0 as 2's compliment)

How do you get from `0xeed0` to 4400?

```javascript
> 0xeed0
61136
```

**Comment by weisjohn** [comment]
Oh, okay, I figured out the complement idea math: `(0xffff - 0xeed0) + 1 == 4400`, but my first question still holds. How do you determine whether or not you need to use the value as it is or the complement?

**Comment by johnnyman727** [comment]
@weisjohn, you can use the builtin [```Buffer.readInt16BE(byteIndex)```](http://nodejs.org/api/buffer.html#buffer_buf_readint16be_offset_noassert), to get the value from the data buffer.

**Comment by johnnyman727** [comment]
@weisjohn, do you think this edit makes it more clear? https://github.com/tessel/ir-attx4/pull/28

**Comment by weisjohn** [comment]
@johnnyman727 absolutely. This was massively helpful!

**Comment by weisjohn** [comment]
I'm ready to close this, if you are.

**Comment by johnnyman727** [comment]
Awesome! I merged the docs PR and I'll close this issue now.
