### ISSUE TITLE
Can't ever read the firmware version and module ID

### ISSUE THREAD

**Issue by snollygolly** [tessel/ir-attx4#31]
On every run of my project, I get the following:

```
Computer:tessel-ir-utility snollygolly$ npm run tessel

> tessel-ir-utility@1.0.0 tessel /Users/snollygolly/tessel-ir-utility
> t2 run index.js

INFO Looking for your Tessel...
INFO Connected to Charmander.
INFO Building project.
INFO Writing project to RAM on Charmander (1744.384 kB)...
INFO Deployed.
INFO Running index.js...
Tessel IR Utility is now listening on http://192.168.1.79:8000
Could not retrieve firmware version and module ID. Attempting update.
Uploading new firmware...
Update finished!
Connected to IR!
```

It looks like it's always updating the firmware, and based on a quick slack conversation with @johnnyman727, that's not expected behavior.

**Comment by johnnyman727** [comment]
Yes, it should check if you have the correct firmware version each time but it definitely should not need to update it each time. Thanks for reporting.

**Comment by johnnyman727** [comment]
@snollygolly want to try out https://github.com/tessel/attiny-common/pull/9?

If it's easier for you, you can just manually update line of `node_modules/attiny-common/lib/index.js` to 200.

**Comment by snollygolly** [comment]
@johnnyman727 200 didn't work for me.  I upped it in increments of 50, and 700 looks to be about the lowest I can go.

**Comment by johnnyman727** [comment]
@snollygolly maybe the best way to approach this would be to continually try to communicate with the module after the reset in 50ms increments until we get a response or 1000ms passes. If 1000ms pass, then we can try to update. Do you want to implement that?

**Comment by snollygolly** [comment]
That sounds like a pretty solid idea.  I'll sure give it a try!

**Comment by johnnyman727** [comment]
:+1: Fantastic. Ping me when you're ready for a review.
